spring:
  application:
    name: prmoquoter
    datasource:
      url: jdbc:h2:mem:prmoquoter;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password: 123456
      platform: h2
      initialization-mode: always
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
